services:
  backend:
    container_name: chat-backend
    build:
      context: ./chat-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  frontend:
    image: chat-frontend
    build:
      context: ./chat-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
